_version: '2.7'
enable_tracing: true
mode: production
crash_provider: sentry
sentry:
  org: grace-studios
  project: newsly-android
repository_provider: github
github:
  repo: samsonpaul87/Newsly-App
  branch: main
